export const TOKENS = {
  colors: {
    bgPage: '#FFFFFF',
    bgCanvas: '#EFEFEA',
    bgCanvasGradientEnd: '#E4EDD9',
    bgCard: '#FFFFFF',
    bgCardInset: '#F5F5F2',
    bgPill: '#ECECE8',
    accent: '#B7CE8F',
    accentText: '#2B3324',
    accentSoft: '#DCE8C8',
    accentBlue: '#A9D3E8',
    textPrimary: '#1A1A18',
    textSecondary: '#5C5C57',
    textTertiary: '#8C8C86',
    textOnDark: '#FFFFFF',
    borderSubtle: '#E8E8E3',
    borderCard: '#ECECE7',
    nodeDark: '#1F1F1D',
    statusDot: '#B7CE8F',
  },
  typography: {
    hero: 'text-[48px] leading-[1.15] font-medium tracking-tight',
    heroMobile: 'text-[32px] leading-[1.2] font-medium tracking-tight',
    sectionH: 'text-[32px] leading-[1.3] font-medium tracking-tight',
    body: 'text-base leading-[1.5] font-normal',
    bodySm: 'text-sm leading-[1.5] font-normal',
    cardLabel: 'text-[11px] leading-[1.4] font-semibold uppercase tracking-wide',
    cardStat: 'text-[28px] leading-none font-medium',
    cardName: 'text-xl leading-[1.2] font-medium',
    cardRole: 'text-sm leading-[1.4] font-normal',
    cardRowLabel: 'text-xs leading-[1.4] font-normal',
    cardRowValue: 'text-[13px] leading-[1.4] font-medium',
  },
  spacing: {
    cardPad: 'p-5',
    canvasPad: 'p-10',
    nodeGap: 'gap-8',
  },
  radius: {
    card: 'rounded-2xl',
    outer: 'rounded-[24px]',
    pill: 'rounded-full',
    avatar: 'rounded-lg',
    nodeDark: 'rounded-full',
  },
  shadows: {
    card: 'shadow-[0_1px_2px_rgba(0,0,0,0.04)]',
    cardHover: 'hover:shadow-[0_4px_12px_rgba(0,0,0,0.06)]',
    outerCanvas: 'shadow-[0_1px_3px_rgba(0,0,0,0.02)]',
    button: 'shadow-[0_1px_2px_rgba(0,0,0,0.06)]',
  }
};
